### ISSUE TITLE
Have a --verbose flag

### ISSUE THREAD

**Issue by renedescartes** [go-to-k/cls3#100]
This is a great product and infact the only way to delete a bucket which has 1M+ objects. 

Would it be possible to do a --verbose flag or something that prints progress? Right now when I run the command it goes into a prolonged period of silence (multi minutes) so it is not clear what % is done. Perhaps it can print the object count or bucket size or some such thing after every delete so a user gets an idea of how long to wait?

Is this doable?

**Comment by go-to-k** [comment]
Hi, @renedescartes 

I'm glad, and thanks for the request!

Perhaps some method is possible. Please give me some time and I will see if there is a better way to do this.

**Comment by renedescartes** [comment]
Thank you. I tested this and works like a charm!
