### ISSUE TITLE
[Feature] asdf plugin mention

### ISSUE THREAD

**Issue by xavbourdeau** [go-to-k/cls3#270]
**Is your feature request related to a problem? Please describe.**
> I have create an asdf plugin for this wonderful utility https://github.com/xavbourdeau/cls3-asdf-plugin

**Describe the solution you'd like**
> Test it and if you are satisfied, you can mention it in the your `README.md`

**Additional context**
> asdf (or asdf-vm) is a wonderful tool that manage all your runtime versions

**Comment by go-to-k** [comment]
@xavbourdeau 

Thanks for your nice plugin and request! That's good.

I will add the docs in the [PR](https://github.com/go-to-k/cls3/pull/271).
