### ISSUE TITLE
I want the choices in interactive mode to show only the region specified

### ISSUE THREAD

**Issue by t4kamura** [go-to-k/cls3#58]
Hi!
The interactive mode is very easy to use. I have a request.

When I try to delete multiple buckets in different regions in interactive mode, I get an error.
I think this is because it tries to delete only the currently specified region.

For example, I have the following buckets.
- dummy1 (ap-northeast-1)
- dummy2 (us-east-1)

If I try to delete them all together, I get the following results.
```sh
cls3 -i -p hoge -f
Filter a keyword of bucket names: dummy

? Select buckets.
 dummy1, dummy2
OK? (Y/n)

INF dummy1 Cleared.
INF dummy1 Deleted.
ERR PermanentRedirectError: Are you sure you are specifying the correct region?
```

In this situation, the deletion of `dummy2` fails because only the default value, `ap-northeast-1`, is specified for the region option.

**It seems that the interactive mode choice should show buckets only for the specified region.**
In the example above, it is assumed that only `dummy1` is shown in the choices.

(In the future, it would be nice to be able to delete across multiple regions.)

**Comment by go-to-k** [comment]
@t4kamura 

Hi! I fixed at the following PR! : https://github.com/go-to-k/cls3/pull/59

And this tool can now be removed even across regions.!

I released new version for this request! : https://github.com/go-to-k/cls3/releases/tag/v0.7.0

**Comment by t4kamura** [comment]
@go-to-k 
Thank you!
I was able to get the operation I wanted!
